fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

user_bundle_app:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

company:
    resource: "@CompanyBundle/Controller/"
    type:     annotation
    prefix:   /

