user_bundle_app_login:
    path:     /login
    defaults: { _controller: UserBundle:Login:login }

user_bundle_app_security_check:
    path: /login_check
    defaults: { _controller: UserBundle:Login:check }

user_bundle_app_logout:
    path:     /logout